spring.application.name=agendador

spring.config.import=optional:file:.env[.properties]

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.web.resources.add-mappings=false
spring.mvc.throw-exception-if-no-handler-found=true

server.forward-headers-strategy=framework

cors.allowed.origins=${CORS_ALLOWED_ORIGINS}
